---
- include_role:
    name: geerlingguy.apache
  vars:
    apache_listen_port: 8090
    apache_global_vhost_settings: |
      Listen 8090
    apache_options: "+Indexes"
    logs_documentroot: "/srv/static/"
    apache_vhosts:
      - servername: "logserver"
        documentroot: "{{ logs_documentroot }}"
        serveralias: ".*"
        extra_parameters: |
          WSGIDaemonProcess logs user=www-data group=www-data processes=8 threads=1
          WSGIProcessGroup logs
          WSGIApplicationGroup %{GLOBAL}
          WSGIScriptAlias /htmlify /usr/local/lib/python2.7/dist-packages/os_loganalyze/wsgi.py

          AddType text/plain .log
          AddType text/plain .sh
          AddType text/plain .yaml
          AddType text/plain .yml

          AddOutputFilterByType DEFLATE text/plain text/html application/x-font-ttf image/svg+xml

          <Directory /usr/local/lib/python2.7/dist-packages/os_loganalyze>
            Allow from all
            Satisfy Any
          </Directory>

          <Directory {{ logs_documentroot }}/periodic*/*>
             IndexOrderDefault Descending Date
          </Directory>

          RewriteEngine On

          RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
          RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME}.gz -f
          RewriteRule ^/(.*)$ %{REQUEST_URI}.gz

          RewriteRule ^/logs/(.*\.(txt|log)\.gz)$ /htmlify/$1 [QSA,L,PT,NS]
          RewriteRule ^/logs/(.*console\.html(\.gz)?)$ /htmlify/$1 [QSA,L,PT,NS]

          RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
          RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
          RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-l
          RewriteCond %{REQUEST_FILENAME} !^/icon
          RewriteRule ^/logs/(.*)$ /htmlify/$1 [QSA,L,PT,NS]

          <FilesMatch \.html\.gz$>
            ForceType text/html
            AddDefaultCharset UTF-8
            AddEncoding x-gzip gz
          </FilesMatch>
          <FilesMatch \.css\.gz$>
            ForceType text/css
            AddDefaultCharset UTF-8
            AddEncoding x-gzip gz
          </FilesMatch>
          <FilesMatch \.js\.gz$>
            ForceType text/javascript
            AddDefaultCharset UTF-8
            AddEncoding x-gzip gz
          </FilesMatch>
          <FilesMatch \.ttf\.gz$>
            ForceType application/x-font-ttf
            AddEncoding x-gzip gz
          </FilesMatch>
          <FilesMatch \.svg\.gz$>
            ForceType image/svg+xml
            AddEncoding x-gzip gz
          </FilesMatch>
          <FilesMatch \.json\.gz$>
            ForceType application/json
            AddEncoding x-gzip gz
          </FilesMatch>
          <FilesMatch \.css$>
            # mod_mime_magic is sometimes passing css files as asm sources
            # e.g css files generated by coverage reports
            ForceType text/css
          </FilesMatch>

          ErrorLog /var/log/apache2/openstack_logs_error.log
          LogLevel warn
          CustomLog /var/log/apache2/openstack_logs_access.log combined
          ServerSignature Off

- include_role:
    name: geerlingguy.apache
  vars:
    apache_listen_port: 80
    apache_vhosts_filename: "50-ci-main.conf"
    apache_vhosts:
      - servername: "logserver"
        serveralias: ".*"
        extra_parameters: |
          RewriteEngine on
          RewriteRule "^/logs$" "/logs/" [R,L]
          RewriteRule "^/logs/(.*)$" "http://localhost:8090/logs/$1" [P]
          ProxyPassReverse "/logs/" "http://localhost:8090/logs/"

          RewriteRule ^/api/connection/(.*)$ http://localhost:9000/api/connection/$1 [P]
          RewriteRule ^/api/console-stream ws://localhost:9000/api/tenant/openstack/console-stream [P]
          RewriteRule ^/api/(.*)$ http://localhost:9000/api/tenant/openstack/$1 [P]

          RewriteCond %{REQUEST_FILENAME} !^/icon
          RewriteRule ^/(.*)$ http://localhost:9000/$1 [P]
