---
- hosts: localhost
  become: true

  roles:
    - role: zuulnodepool
      when: '"zuul" in services'
    - role: logserver
      when: '"logserver" in services'
    - role: apache
      when: '"logserver" in sevices and "zuul" in services'
