---
- hosts: localhost
  vars:
    roles:
      - name: ansible-role-zookeeper
        repo: https://github.com/openstack/ansible-role-zookeeper
      - name: ansible-role-diskimage-builder
        repo: https://github.com/openstack/ansible-role-diskimage-builder
      - name: ansible-role-nodepool
        repo: https://github.com/openstack/ansible-role-nodepool
      - name: ansible-role-zuul
        repo: https://github.com/openstack/ansible-role-zuul
  tasks:
    - name: Fetch role
      git:
        repo: "{{item.repo}}"
        dest: "/opt/{{item.name}}"
      with_items: "{{ roles }}"

    - include_role:
        name: "/opt/{{ item.name }}"
      with_items: "{{ roles }}"
