---
- hosts: localhost
  vars:
    roles:
      - name: ansible-role-zookeeper
        repo: https://github.com/openstack/ansible-role-zookeeper
      - name: ansible-role-diskimage-builder
        repo: https://github.com/openstack/ansible-role-diskimage-builder
      - name: ansible-role-nodepool
        repo: https://github.com/openstack/ansible-role-nodepool
      - name: ansible-role-zuul
        repo: https://github.com/openstack/ansible-role-zuul
    nodepool_install_method: git
    zuul_file_main_yaml_src: files/main.yaml
    zuul_file_zuul_conf_src: files/zuul.conf
    nodepool_file_nodepool_yaml_src: files/nodepool.yaml
  tasks:
    - name: Install bubblewrap
      package:
        name: bubblewrap
      ignore_errors: true
      become: true

    - name: Fetch role
      git:
        repo: "{{item.repo}}"
        dest: "/etc/ansible/roles/{{item.name}}"
      with_items: "{{ roles }}"
      become: true

    - name: Run nodepool pre install phase
      include_role:
        name: ansible-role-nodepool
      vars:
        nodepool_task_manager:
          - pre

    - name: Allow passwordless sudo for nodepool
      lineinfile:
        dest: /etc/sudoers.d/nodepool
        create: yes
        state: present
        regexp: '^%nodepool'
        line: '%nodepool ALL=NOPASSWD: ALL'
        validate: visudo -cf %s
      become: true

    - name: Create config directory for clouds
      file:
        path: "~/.config/openstack"
        state: directory
      become: true
      become_user: nodepool

    - name: Create clouds.yaml for nodepool user
      template:
        src: clouds.yaml
        dest: "~/.config/openstack/clouds.yaml"
      become: true
      become_user: nodepool

    - include_role:
        name: "{{item.name}}"
      with_items: "{{ roles }}"

    - name: Generate Zuul SSH key
      shell:
        ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
      args:
        creates: "~/.ssh/id_rsa"
      become: true
      become_user: zuul

    - name: Scan SSH host key for review.openstack.org
      shell:
        ssh-keyscan -t rsa -p 29418 review.openstack.org
      register: openstack_keyscan

    - name: Add review.openstack.org to zuul known_hosts
      known_hosts:
        name: "[review.openstack.org]:29418"
        key: "{{ openstack_keyscan.stdout }}"
        path: "~/.ssh/known_hosts"
      become: true
      become_user: zuul

    - name: Find zuul install location
      shell: |
        find / -type d -wholename "*zuul/web"
      register: zuul_path_raw
      become: true

    - name: Make zuul web static directory
      file:
        path: "{{ zuul_path_raw.stdout }}/static"
        state: directory
      become: true

    - name: Download and install zuul dashboard files
      shell: |
        wget http://tarballs.openstack.org/zuul/zuul-content-latest.tar.gz
        tar -xzvf zuul-content-latest.tar.gz -C {{ zuul_path_raw.stdout }}/static
      args:
        creates: "{{ zuul_path_raw.stdout }}/static/status.html"
      become: true
