---
ci_roles:
  - name: ansible-role-zookeeper
    repo: https://github.com/openstack/ansible-role-zookeeper
  - name: ansible-role-diskimage-builder
    repo: https://github.com/openstack/ansible-role-diskimage-builder
  - name: ansible-role-nodepool
    repo: https://github.com/openstack/ansible-role-nodepool
  - name: ansible-role-zuul
    repo: https://github.com/openstack/ansible-role-zuul

labels_min_ready: {}
