---
ci_roles:
  - name: ansible-role-zookeeper
    repo: https://github.com/openstack/ansible-role-zookeeper
  - name: ansible-role-diskimage-builder
    repo: https://github.com/openstack/ansible-role-diskimage-builder
  - name: ansible-role-nodepool
    repo: https://github.com/openstack/ansible-role-nodepool
  - name: ansible-role-zuul
    repo: https://github.com/openstack/ansible-role-zuul
nodepool_install_method: git
zuul_file_main_yaml_src: files/main.yaml
zuul_file_zuul_conf_src: templates/zuul.conf
nodepool_file_nodepool_yaml_src: files/nodepool.yaml
nodepool_file_nodepool_launcher_service_config_src: files/nodepool-enable-webapp.conf
