---
logs_documentroot: "/srv/static/logs"
apache_vhosts:
  - servername: "3ci-log.ciscolabs.net"
    serveralias: ".*"
    documentroot: "{{ logs_documentroot }}"
    extra_parameters: |
      WSGIDaemonProcess logs user=www-data group=www-data processes=8 threads=1
      WSGIProcessGroup logs
      WSGIApplicationGroup %{GLOBAL}
      WSGIScriptAlias /htmlify /usr/local/lib/python2.7/dist-packages/os_loganalyze/wsgi.py

      AddType text/plain .log
      AddType text/plain .sh
      AddType text/plain .yaml
      AddType text/plain .yml

      AddOutputFilterByType DEFLATE text/plain text/html application/x-font-ttf image/svg+xml

      <Directory /usr/local/lib/python2.7/dist-packages/os_loganalyze>
        Allow from all
        Satisfy Any
      </Directory>

      <Directory {{ logs_documentroot }}/periodic*/*>
         IndexOrderDefault Descending Date
      </Directory>

      RewriteEngine On

      RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
      RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME}.gz -f
      RewriteRule ^/(.*)$ %{REQUEST_URI}.gz

      RewriteRule ^/(.*\.(txt|log)\.gz)$ /htmlify/$1 [QSA,L,PT,NS]
      RewriteRule ^/(.*console\.html(\.gz)?)$ /htmlify/$1 [QSA,L,PT,NS]

      RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
      RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
      RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-l
      RewriteCond %{REQUEST_FILENAME} !^/icon
      RewriteRule ^/(.*)$ /htmlify/$1 [QSA,L,PT,NS]

      <FilesMatch \.html\.gz$>
        ForceType text/html
        AddDefaultCharset UTF-8
        AddEncoding x-gzip gz
      </FilesMatch>
      <FilesMatch \.css\.gz$>
        ForceType text/css
        AddDefaultCharset UTF-8
        AddEncoding x-gzip gz
      </FilesMatch>
      <FilesMatch \.js\.gz$>
        ForceType text/javascript
        AddDefaultCharset UTF-8
        AddEncoding x-gzip gz
      </FilesMatch>
      <FilesMatch \.ttf\.gz$>
        ForceType application/x-font-ttf
        AddEncoding x-gzip gz
      </FilesMatch>
      <FilesMatch \.svg\.gz$>
        ForceType image/svg+xml
        AddEncoding x-gzip gz
      </FilesMatch>
      <FilesMatch \.json\.gz$>
        ForceType application/json
        AddEncoding x-gzip gz
      </FilesMatch>
      <FilesMatch \.css$>
        # mod_mime_magic is sometimes passing css files as asm sources
        # e.g css files generated by coverage reports
        ForceType text/css
      </FilesMatch>

      ErrorLog /var/log/apache2/openstack_logs_error.log
      LogLevel warn
      CustomLog /var/log/apache2/openstack_logs_access.log combined
      ServerSignature Off
apache_mods_enabled:
  - rewrite.load
  - proxy.load
  - proxy_http.load
  - wsgi.load
apache_remove_default_vhost: true
apache_options: |
  +Indexes
apache_vhosts_filename: "99-ci-logs.conf"
