clouds:
  mycloud:
    auth:
      username: demo
      password: password
      project_name: demo
      user_domain_name: Default
      project_domain_name: Default
      auth_url: http://127.0.0.1/identity/v3
    region_name: RegionOne
